/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ufpr.br.opla.gui2;

import java.awt.HeadlessException;
import java.io.File;
import java.io.FileNotFoundException;
import java.util.ArrayList;
import java.util.List;
import java.util.concurrent.ExecutionException;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author elf
 */
public class main extends javax.swing.JFrame {

    private ManagerApplicationConfig config = null;
//     private OplaServices oplaService = null;
    private String pathSmartyBck;
    private String pathConcernBck;
    private String pathRelationchipBck;
    private String pathPatternBck;

    /**
     * Creates new form main
     */
    public main() throws ExecutionException {
        initComponents();

        try {
            config = new ManagerApplicationConfig();
            //     oplaService = new OplaServices(config);
        } catch (FileNotFoundException ex) {
            JOptionPane.showMessageDialog(null, "Configuration file config/application.yaml not found. ");
            System.exit(0);
        }
        
        //Text Field are disabled
        fieldSmartyProfile.setEditable(false);
        fieldConcernProfile.setEditable(false);
        fieldPatterns.setEditable(false);      
        fieldRelationships.setEditable(false);        
                
                
        GuiServices guiservices = new GuiServices(config);
        guiservices.configureSmartyProfile(fieldSmartyProfile, checkSmarty, btnSmartyProfile);
        guiservices.configureConcernsProfile(fieldConcernProfile, checkConcerns, btnConcernProfile);
        guiservices.configurePatternsProfile(fieldPatterns, checkPatterns, btnPatternProfile);
        guiservices.configureRelationshipsProfile(fieldRelationships, checkRelationship, btnRelationshipProfile);
        guiservices.configureTemplates(fieldTemplate);
        guiservices.configureLocaleToSaveModels(fieldManipulationDir);

        guiservices.configureLocaleToExportModels(fieldOutput);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        fieldSmartyProfile = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        fieldConcernProfile = new javax.swing.JTextField();
        btnSmartyProfile = new javax.swing.JButton();
        btnConcernProfile = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnInput = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        fieldTemplate = new javax.swing.JTextField();
        btnTemplate = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        fieldPatterns = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        fieldRelationships = new javax.swing.JTextField();
        btnPatternProfile = new javax.swing.JButton();
        btnRelationshipProfile = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        fieldOutput = new javax.swing.JTextField();
        btnOutput = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        fieldManipulationDir = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        fieldArchitectureInput = new javax.swing.JTextArea();
        btnCleanListArchs = new javax.swing.JButton();
        btnManipulationDir = new javax.swing.JButton();
        checkSmarty = new javax.swing.JCheckBox();
        checkConcerns = new javax.swing.JCheckBox();
        checkRelationship = new javax.swing.JCheckBox();
        checkPatterns = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setText("SMarty Profile:");

        fieldSmartyProfile.setName("pathToSmarty"); // NOI18N
        fieldSmartyProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldSmartyProfileActionPerformed(evt);
            }
        });

        jLabel2.setText("Concerns Profile:");

        fieldConcernProfile.setName("sdfs"); // NOI18N
        fieldConcernProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldConcernProfileActionPerformed(evt);
            }
        });

        btnSmartyProfile.setText("Browser...");
        btnSmartyProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSmartyProfileActionPerformed(evt);
            }
        });

        btnConcernProfile.setText("Browser...");
        btnConcernProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConcernProfileActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel3.setText("Templates Configuration");
        jLabel3.setToolTipText("");

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel4.setText("Manipulation Directory");

        jLabel5.setText("A list of paths separated by comma");

        btnInput.setText("Confirme");
        btnInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInputActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel6.setText("Profiles Configuration");

        jLabel7.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N
        jLabel7.setText("about templates");
        jLabel7.setToolTipText("<html><h3>About Templtes</h3><br/>\n\nTexto explicando brevemente o que são os templates e para que servem.");

        jLabel8.setText("Templates Directory:");

        btnTemplate.setText("Select a Directory...");
        btnTemplate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTemplateActionPerformed(evt);
            }
        });

        jLabel9.setText("Patterns Profile:");

        fieldPatterns.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldPatternsActionPerformed(evt);
            }
        });

        jLabel10.setText("Relationships Profile:");

        btnPatternProfile.setText("Browser...");
        btnPatternProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPatternProfileActionPerformed(evt);
            }
        });

        btnRelationshipProfile.setText("Browser...");
        btnRelationshipProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRelationshipProfileActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel11.setText("Architecture(s) list");

        jLabel12.setText("Output:");

        fieldOutput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldOutputActionPerformed(evt);
            }
        });

        btnOutput.setText("Browser...");
        btnOutput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOutputActionPerformed(evt);
            }
        });

        jButton1.setText("Visualize your application.yaml file");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel13.setText("Select where you want save outputs");

        jLabel14.setText("about manipulation directory");

        jLabel15.setText("Directory");

        fieldArchitectureInput.setColumns(20);
        fieldArchitectureInput.setRows(5);
        jScrollPane1.setViewportView(fieldArchitectureInput);

        btnCleanListArchs.setText("Clean");
        btnCleanListArchs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCleanListArchsActionPerformed(evt);
            }
        });

        btnManipulationDir.setText("Browser...");
        btnManipulationDir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManipulationDirActionPerformed(evt);
            }
        });

        checkSmarty.setText("SMarty");
        checkSmarty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkSmartyActionPerformed(evt);
            }
        });

        checkConcerns.setText("Concerns");
        checkConcerns.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkConcernsActionPerformed(evt);
            }
        });

        checkRelationship.setText("Relationship");
        checkRelationship.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkRelationshipActionPerformed(evt);
            }
        });

        checkPatterns.setText("Patterns");
        checkPatterns.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkPatternsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(checkSmarty)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(checkConcerns)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(checkRelationship)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(checkPatterns)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addGap(235, 235, 235))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(jLabel2))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(fieldConcernProfile, javax.swing.GroupLayout.DEFAULT_SIZE, 421, Short.MAX_VALUE)
                                            .addComponent(fieldSmartyProfile))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btnConcernProfile, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(btnSmartyProfile))))
                                .addGap(46, 46, 46)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(fieldRelationships, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnRelationshipProfile))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(4, 4, 4)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(fieldPatterns, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(btnPatternProfile))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(6, 6, 6)
                                                .addComponent(jLabel10))))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel8))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(fieldTemplate, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel7)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnTemplate, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(fieldManipulationDir, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnManipulationDir))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(176, 176, 176)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel4)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel14))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(12, 12, 12)
                                                .addComponent(jLabel15))))))
                            .addComponent(jLabel11)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(263, 263, 263)
                                .addComponent(jLabel13)))
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(221, 221, 221)
                                .addComponent(btnInput)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnCleanListArchs))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(89, 89, 89)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(fieldOutput, javax.swing.GroupLayout.PREFERRED_SIZE, 387, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnOutput))
                            .addComponent(jLabel12))
                        .addGap(0, 142, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel9)
                        .addGap(448, 448, 448))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(checkSmarty)
                            .addComponent(checkConcerns)
                            .addComponent(checkRelationship)
                            .addComponent(checkPatterns))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldSmartyProfile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSmartyProfile)
                    .addComponent(fieldPatterns, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPatternProfile))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldConcernProfile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnConcernProfile)
                    .addComponent(fieldRelationships, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRelationshipProfile))
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel7)
                    .addComponent(jLabel4)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldTemplate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTemplate)
                    .addComponent(fieldManipulationDir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnManipulationDir))
                .addGap(33, 33, 33)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(fieldOutput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnOutput))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnInput)
                    .addComponent(btnCleanListArchs))
                .addContainerGap(58, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Path Confs", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        jTabbedPane1.getAccessibleContext().setAccessibleName("Paths Confs");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnConcernProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConcernProfileActionPerformed
        String newPath = fileChooser(fieldConcernProfile, "uml");
        if (newPath.equals("")) {
            this.config.updatePathToProfileConcerns(fieldConcernProfile.getText());
        } else {
            this.config.updatePathToProfileConcerns(newPath);
        }
    }//GEN-LAST:event_btnConcernProfileActionPerformed

    private void btnSmartyProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSmartyProfileActionPerformed
        String newPath = fileChooser(fieldSmartyProfile, "uml");
        if (newPath.equals("")) {
            this.config.updatePathToProfileSmarty(fieldSmartyProfile.getText());
        } else {
            this.config.updatePathToProfileSmarty(newPath);
        }
    }//GEN-LAST:event_btnSmartyProfileActionPerformed

    private void fieldConcernProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldConcernProfileActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldConcernProfileActionPerformed

    private void fieldSmartyProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldSmartyProfileActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldSmartyProfileActionPerformed

    private void btnTemplateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTemplateActionPerformed
        String path = dirChooser(fieldTemplate);
        if ("".equals(path)) {
            this.config.updatePathToTemplateFiles(fieldTemplate.getText());
        } else {
            this.config.updatePathToTemplateFiles(path);
        }
    }//GEN-LAST:event_btnTemplateActionPerformed

    private String dirChooser(JTextField field) throws HeadlessException {
        JFileChooser c = new JFileChooser();
        String path;
        c.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        int rVal = c.showOpenDialog(this);
        if (rVal == JFileChooser.APPROVE_OPTION) {
            path = c.getSelectedFile().getAbsolutePath();
            field.setText(path);
            field.updateUI();
            return path;
        }
        return "";
    }

    private void btnRelationshipProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRelationshipProfileActionPerformed
        String newPath = fileChooser(fieldRelationships, "uml");
        if (newPath.equals("")) {
            this.config.updatePathToProfileRelationships(fieldRelationships.getText());
        } else {
            this.config.updatePathToProfileRelationships(newPath);
        }
    }//GEN-LAST:event_btnRelationshipProfileActionPerformed

    private void fieldPatternsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldPatternsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldPatternsActionPerformed

    private void btnPatternProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPatternProfileActionPerformed
        String newPath = fileChooser(fieldPatterns, "uml");
        if ("".equals(newPath)) {
            this.config.updatePathToProfilePatterns(fieldPatterns.getText());
        } else {
            this.config.updatePathToProfilePatterns(newPath);
        }
    }//GEN-LAST:event_btnPatternProfileActionPerformed

    private void btnOutputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOutputActionPerformed
        String path = dirChooser(fieldOutput);
        if ("".equals(path)) {
            this.config.updatePathToExportModels(fieldOutput.getText());
        } else {
            this.config.updatePathToExportModels(path);
        }

    }//GEN-LAST:event_btnOutputActionPerformed

    private void fieldOutputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldOutputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldOutputActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        StringBuffer sb = new StringBuffer();
        sb.append("Application.yml file content").append("\n\n");
        sb.append("directoryToExportModels:").append(config.getConfig().getDirectoryToExportModels()).append("\n");
        sb.append("pathToProfile:").append(config.getConfig().getPathToProfile()).append("\n");
        sb.append("pathToProfileConcern:").append(config.getConfig().getPathToProfileConcern()).append("\n");
        sb.append("pathToProfilePatterns").append(config.getConfig().getPathToProfilePatterns()).append("\n");
        sb.append("pathToProfileRelationships").append(config.getConfig().getPathToProfileRelationships()).append("\n");
        sb.append("pathToTemplateModelsDirectory").append(config.getConfig().getPathToTemplateModelsDirectory()).append("\n");
        JOptionPane.showMessageDialog(null, sb);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInputActionPerformed
        String archs[] = fieldArchitectureInput.getText().split(",");
        List<String> invalidEntries = validateEntries(archs);

        if (invalidEntries.isEmpty()) {
            VolatileConfs.setArchitectureInputPath(archs);
        } else {
            JOptionPane.showMessageDialog(null, "There invalid entries for architecture list. Check it please");
        }
    }//GEN-LAST:event_btnInputActionPerformed

    private void btnCleanListArchsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCleanListArchsActionPerformed
        fieldArchitectureInput.setText("");
        VolatileConfs.setArchitectureInputPath(null);
    }//GEN-LAST:event_btnCleanListArchsActionPerformed

    private void btnManipulationDirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManipulationDirActionPerformed
        String path = dirChooser(fieldManipulationDir);
        if ("".equals(path)) {
            this.config.updatePathToSaveModels(fieldManipulationDir.getText());
        } else {
            this.config.updatePathToSaveModels(path);
        }
    }//GEN-LAST:event_btnManipulationDirActionPerformed

    private void checkSmartyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkSmartyActionPerformed
        if(!checkSmarty.isSelected()){
            fieldSmartyProfile.setText(pathSmartyBck);
            btnSmartyProfile.setEnabled(true);
            this.config.updatePathToProfileSmarty(pathSmartyBck);
        }else{
            pathSmartyBck = fieldSmartyProfile.getText();
            fieldSmartyProfile.setText("");
            this.config.updatePathToProfileSmarty("");
            btnSmartyProfile.setEnabled(false);
        }
    }//GEN-LAST:event_checkSmartyActionPerformed

    private void checkConcernsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkConcernsActionPerformed
        if(!checkConcerns.isSelected()){
            fieldConcernProfile.setText(pathConcernBck);
            btnConcernProfile.setEnabled(true);
            this.config.updatePathToProfileConcerns(pathConcernBck);
        }else{
            pathConcernBck = fieldConcernProfile.getText();
            fieldConcernProfile.setText("");
            this.config.updatePathToProfileConcerns("");
            btnConcernProfile.setEnabled(false);
        }
    }//GEN-LAST:event_checkConcernsActionPerformed

    private void checkRelationshipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkRelationshipActionPerformed
       if(!checkRelationship.isSelected()){
            fieldRelationships.setText(pathRelationchipBck);
            btnRelationshipProfile.setEnabled(true);
            this.config.updatePathToProfileRelationships(pathRelationchipBck);
        }else{
            pathRelationchipBck = fieldRelationships.getText();
            fieldRelationships.setText("");
            this.config.updatePathToProfileRelationships("");
            btnRelationshipProfile.setEnabled(false);
        }
    }//GEN-LAST:event_checkRelationshipActionPerformed

    private void checkPatternsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkPatternsActionPerformed
       if(!checkPatterns.isSelected()){
            fieldPatterns.setText(pathPatternBck);
            btnPatternProfile.setEnabled(true);
            this.config.updatePathToProfilePatterns(pathPatternBck);
        }else{
            pathPatternBck = fieldPatterns.getText();
            fieldPatterns.setText("");
            this.config.updatePathToProfilePatterns("");
            btnPatternProfile.setEnabled(false);
        }
    }//GEN-LAST:event_checkPatternsActionPerformed

    private String fileChooser(JTextField fieldToSet, String allowExtension) throws HeadlessException {
        JFileChooser c = new JFileChooser();
        int rVal = c.showOpenDialog(this);
        if (rVal == JFileChooser.APPROVE_OPTION) {

            File f = new File(c.getCurrentDirectory() + c.getSelectedFile().getName());
            String ext = FilesManager.getExtension(f);

            if (!ext.equalsIgnoreCase(allowExtension)) {
                JOptionPane.showMessageDialog(null, "The selected file is not allowed. You need selects a file with extension .uml, but you selects a ." + ext + " file");
                return "";
            } else {
                final String path = c.getCurrentDirectory() + "/" + c.getSelectedFile().getName();
                fieldToSet.setText(path);
                fieldToSet.updateUI();
                return path;

            }
        }

        return "";

    }
    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCleanListArchs;
    private javax.swing.JButton btnConcernProfile;
    private javax.swing.JButton btnInput;
    private javax.swing.JButton btnManipulationDir;
    private javax.swing.JButton btnOutput;
    private javax.swing.JButton btnPatternProfile;
    private javax.swing.JButton btnRelationshipProfile;
    private javax.swing.JButton btnSmartyProfile;
    private javax.swing.JButton btnTemplate;
    private javax.swing.JCheckBox checkConcerns;
    private javax.swing.JCheckBox checkPatterns;
    private javax.swing.JCheckBox checkRelationship;
    private javax.swing.JCheckBox checkSmarty;
    private javax.swing.JTextArea fieldArchitectureInput;
    private javax.swing.JTextField fieldConcernProfile;
    private javax.swing.JTextField fieldManipulationDir;
    private javax.swing.JTextField fieldOutput;
    private javax.swing.JTextField fieldPatterns;
    private javax.swing.JTextField fieldRelationships;
    private javax.swing.JTextField fieldSmartyProfile;
    private javax.swing.JTextField fieldTemplate;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables

    private List<String> validateEntries(String[] archs) {
        List<String> invalidsEntries = new ArrayList<String>();

        for (int i = 0; i < archs.length; i++) {
            String arch = archs[i].substring(archs[i].indexOf('.'), archs[i].length());
            if (!arch.equalsIgnoreCase(".uml")) {
                invalidsEntries.add(archs[i]);
            }
        }

        return invalidsEntries;
    }

 
}
