--- 
directoryToExportModels: testeFinal/
directoryToSaveModels: manipulation/
pathToProfile: /Users/elf/oplatool/profiles/smarty.profile.uml
pathToProfileConcern: /Users/elf/mestrado/agmfinal/perfilConcerns.profile.uml
pathToProfilePatterns: /Users/elf/mestrado/agmfinal/smarty.profile.uml
pathToProfileRelationships: /profiles/relationships.profile.uml
pathToTemplateModelsDirectory: /Users/elf/oplatool/templates/
