--- 
directoryToExportModels: /Users/elf/Backup
directoryToSaveModels: manipulation/
pathToProfile: /Users/elf/mestrado/agmfinal/perfilConcerns.profile.uml
pathToProfileConcern: /Users/elf/mestrado/agmfinal/perfilConcerns.profile.uml
pathToProfilePatterns: /Users/elf/mestrado/agmfinal/agm.uml
pathToProfileRelationships: /profiles/relationships.profile.uml
pathToTemplateModelsDirectory: /Users/elf/dev
