--- 
directoryToExportModels: /Users/elf/Documents
directoryToSaveModels: /Users/elf/oplatool/temp
pathToProfile: /Users/elf/oplatool/profiles/smarty.profile.uml
pathToProfileConcern: /Users/elf/oplatool/profiles/concerns.profile.uml
pathToProfilePatterns: /Users/elf/oplatool/profiles/patterns.profile.uml
pathToProfileRelationships: /Users/elf/oplatool/profiles/relationships.profile.uml
pathToTemplateModelsDirectory: /Users/elf/oplatool/templates/
